export const mockData = [{"id":1,"author":"Arthur","content":"duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec"},
{"id":2,"author":"Letitia","content":"amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere"},
{"id":3,"author":"Emeline","content":"sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in"},
{"id":4,"author":"Carol-jean","content":"nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor"},
{"id":5,"author":"Cos","content":"gravida nisi at nibh in hac habitasse platea dictumst aliquam"},
{"id":6,"author":"Siegfried","content":"parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes"},
{"id":7,"author":"Emmalyn","content":"lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at"},
{"id":8,"author":"Batsheva","content":"sapien placerat ante nulla justo aliquam quis turpis eget elit sodales"},
{"id":9,"author":"Carrol","content":"sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper"},
{"id":10,"author":"Shawnee","content":"sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada"},
{"id":11,"author":"Susie","content":"felis fusce posuere felis sed lacus morbi sem mauris laoreet ut"},
{"id":12,"author":"Svend","content":"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper"},
{"id":13,"author":"Adolphus","content":"sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in"},
{"id":14,"author":"Kirbee","content":"mi integer ac neque duis bibendum morbi non quam nec dui"},
{"id":15,"author":"Carmine","content":"morbi vestibulum velit id pretium iaculis diam erat fermentum justo"},
{"id":16,"author":"Tyrone","content":"vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget"},
{"id":17,"author":"Gabriello","content":"nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis"},
{"id":18,"author":"Marinna","content":"pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices"},
{"id":19,"author":"Candide","content":"vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum"},
{"id":20,"author":"Rikki","content":"vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere"}]